openapi: 3.0.3
info:
    title: API Dự án tốt nghiệp
    description: |-
        Đây là API dự án tốt nghiệp do Datlt34 master thực hiện
    version: 1.0.1
servers:
    - url: http://localhost:8080/api
    - url: http://swagger.io/v1
tags:
    - name: auth
      description: Liên quan đến đăng ký, đăng nhập
paths:
    /signup:
        post:
            tags:
                - auth
            summary: Đăng ký
            description: Tạo tài khoản người dùng
            operationId: signup
            requestBody:
                description: Thông tin đăng ký tài khoản mới
                content:
                    application/json:
                        schema:
                            type: "object"
                            properties:
                                name:
                                    type: "string"
                                    example: "Le Trong Dat"
                                email:
                                    type: "string"
                                    example: "member@gmail.com"
                                password:
                                    type: "string"
                                    example: "123456"
                                confirmPassword:
                                    type: "string"
                                    example: "123456"
                required: true
            responses:
                "201":
                    description: Đăng ký tài khoản thành công
                    content:
                        application/json:
                            schema:
                                type: "object"
                                properties:
                                    message:
                                        type: "string"
                                        example: "Tạo tài khoản thành công"
                                    accessToken:
                                        type: "string"
                                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NjAwNzk2YTViYzRjYmFhOTc5MjFkYSIsImlhdCI6MTcwMDc5MjIxNCwiZXhwIjoxNzAwODc4NjE0fQ.WxuWkB0GTkWiGcj3LuMSw_9vDOlPt7QUsu6lRRDX9D0"
                                    user:
                                        type: "object"
                                        properties:
                                            name:
                                                type: "string"
                                                example: "Le Trong Dat"
                                            email:
                                                type: "string"
                                                example: "member@gmail.com"
                                            role:
                                                type: "string"
                                                example: "member"
                                            _id:
                                                type: "string"
                                                example: "65600796a5bc4cbaa97921da"
                                            createdAt:
                                                type: "string"
                                                example: "2023-11-24T02:16:54.058Z"
                                            updatedAt:
                                                type: "string"
                                                example: "2023-11-24T02:16:54.058Z"
                "400":
                    description: Lỗi gì đó từ server
                "404":
                    description: Pet not found
                "405":
                    description: Validation exception
